version: '3.9'

networks:
  my-net:
    name: my-net
    driver: bridge

# networks:
#   default:
#     external: true
#     name: my-net

services:
  dynamodb-local:
    command: '-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data'
    image: 'amazon/dynamodb-local:latest'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: dynamodb-local
    ports:
      - '8000:8000'
    volumes:
      - './docker/dynamodb:/home/dynamodblocal/data'
    working_dir: /home/dynamodblocal

  app-node:
    depends_on:
      - dynamodb-local
    image: banst/awscli
    container_name: app-node
    ports:
      - '8080:8080'
    environment:
      AWS_ACCESS_KEY_ID: 'MY_ACCESS_KEY_ID'
      AWS_SECRET_ACCESS_KEY: 'MY_SECRET_ACCESS_KEY'
      AWS_REGION: 'ap-northest-2'
    command: dynamodb describe-limits --endpoint-url http://dynamodb-local:8000 --region us-west-2
