version: '3.9'

networks:
  my-net:
    name: my-net
    driver: bridge

# networks:
#   default:
#     external: true
#     name: my-net

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 8000:8000
    volumes:
      - /var/docker/dynamodb:/home/dynamodblocal/data
    command: '-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath /home/dynamodblocal/data/'

