version: "3.8"

services:
  neo4j-db:
    image: neo4j:latest
    container_name: neo4j-db
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/mypassword
      - NEO4J_dbms_logs_debug_level=DEBUG
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_apoc_uuid_enabled=true
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_dbms_default__listen__address=0.0.0.0

    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/plugins:/plugins
      - ./neo4j_db/import:/import

volumes:
  neo4j_db:
