version: '3.9'

# Create `my-net`
networks:
  my-net:
    driver: bridge

services:
  postgis-db:
    image: kartoza/postgis:14-3.2
    container_name: postgis-db
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "5432:5432"
    networks:
      - my-net
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology,postgis_raster,pgrouting
    volumes:
      - /var/docker/postgis:/var/lib/postgresql