version: "3.9"

networks:
  default:
    external: true
    name: my_net

services:
  sonarqube:
    image: sonarqube:latest
    command: -Dsonar.ce.javaOpts=-Xmx1192m -Dsonar.web.javaOpts=-Xmx1192m -Dsonar.search.javaAdditionalOpts=-Dnode.store.allow_mmap=false
    container_name: sonarqube
    ports:
      - 9000:9000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgresql-db:5432/sonar # `postgresql-db` is a container name

