version: '3.9'

# Create `my-net`
networks:
  my-net:
    name: my-net
    driver: bridge

## But if `my-net` is exists, use it
# networks:
#   default:
#     external: true
#     name: my-net

services:
  sonarqube:
    image: sonarqube:8.9.9-community
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: sonarqube
    command: -Dsonar.ce.javaOpts=-Xmx1192m -Dsonar.web.javaOpts=-Xmx1192m -Dsonar.search.javaAdditionalOpts=-Dnode.store.allow_mmap=false
    ports:
      - 9000:9000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://postgresql-db:5432/sonar # `postgresql-db` is a container name