version: '3.9'

# Create `my-net`
networks:
  my-net:
    name: my-net
    driver: bridge

## But if `my-net` is exists, use it
# networks:
#   default:
#     external: true
#     name: my-net

services:
  postgresql-db:
    image: postgres:12
    container_name: postgresql-db
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 5432:5432
    networks:
      - my-net
    environment:
      - DEBUG=false
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - HASURA_DB=hasura
      - HASURA_USER=hasura
      - HASURA_PASSWORD=hasura
      - SONAR_DB=sonar
      - SONAR_USER=sonar
      - SONAR_PASSWORD=sonar
    volumes:
      - /var/docker/init/:/docker-entrypoint-initdb.d/
      - /var/docker/postgresql/data:/var/lib/postgresql/data
