version: "3.9"

networks:
  db_net:
    name: db_net
    driver: bridge

volumes:
  db_data:

services:
  postgresql-db:
    image: postgres:12
    container_name: postgresql-db
    ports:
      - 5432:5432
    networks:
      - db_net
    environment:
      - DEBUG=false
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
