version: "3.9"

# Create `my_net` if exists use it
networks:
  my_net:
    name: my_net
    driver: bridge

# Use `my_net`
# networks:
#   default:
#     external: true
#     name: my_net

volumes:
  db_data:

services:
  postgresql-db:
    image: postgres:12
    container_name: postgresql-db
    ports:
      - 5432:5432
    networks:
      - my_net
    environment:
      - DEBUG=false
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - HASURA_DB=hasura
      - HASURA_USER=hasura
      - HASURA_PASSWORD=hasura
      - SONAR_DB=sonar
      - SONAR_USER=sonar
      - SONAR_PASSWORD=sonar
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
      - ./db_data:/var/lib/postgresql/data
