version: '3.9'

networks:
  swagger_link:
    external: true

services:
  swagger-editor:
    image: swaggerapi/swagger-editor
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: 'swagger-editor'
    ports:
      - 9011:8080

  swagger-ui:
    image: swaggerapi/swagger-ui
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: 'swagger-ui'
    ports:
      - 9012:8080
    volumes:
      - /var/docker/swagger/api/v1/openapi.json:/api/v1/openapi.json
    environment:
      SWAGGER_JSON: /api/v1/openapi.json
      # API_URL: ''

  swagger-api:
    image: danielgtaylor/apisprout
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: 'swagger-api'
    ports:
      - 9013:8000
    volumes:
      - /var/docker/swagger/api/v1/openapi.json:/api/v1/openapi.json
    command: /api/v1/openapi.json
    networks:
      swagger_link:
        aliases:
          - local.swagger.apisprout

  swagger-nginx:
    image: nginx:mainline-alpine
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: 'swagger-nginx'
    ports:
      - 9014:8084
    volumes:
      - /var/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      swagger_link:
        aliases:
          - local.swagger.api
