version: "3.9"
# Create `my-net`
networks:
  my-net:
    name: my-net
    driver: bridge
## But if `my-net` is exists, use it
# networks:
#   default:
#     external: true
#     name: my-net
services:
  sqs-mq:
    image: "roribio16/alpine-sqs:latest"
    container_name: sqs-mq
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 9324:9324
      - 9325:9325
    networks:
      - my-net
