version: "3.9"
# Create `my-net`
networks:
  my-net:
    driver: bridge

services:
  sqs-mq:
    image: "roribio16/alpine-sqs:latest"
    container_name: sqs-mq
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 9324:9324
      - 9325:9325
    networks:
      - my-net
