version: "3.9"
# Create `my-net`
networks:
  my-net:
    driver: bridge

services:
  elasticmq-mq:
    image: "softwaremill/elasticmq:latest"
    container_name: elasticmq-mq
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 9324:9324
      - 9325:9325
    networks:
      - my-net
