version: '3.9'

# Create `my-net`
networks:
  my-net:
    driver: bridge

services:
  grafana-db:
    image: 'grafana/grafana:latest'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: grafana
    ports:
      - 3300:3000
