version: '3.9'

# Create `default`
networks:
  default:
    driver: bridge

services:
  grafana-db:
    image: 'grafana/grafana:latest'
    container_name: grafana
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "3300:3000"
