version: "3.9"

networks:
  my_net:
    name: my_net
    driver: bridge

# networks:
#   default:
#     external: true
#     name: my_net

volumes:
  gitlab:

services:
  gitlab:
    image: "gitlab/gitlab-ee:latest"
    container_name: gitlab
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 80:80
      - 443:443
      - 22:22
    environment:
      - TZ='Asia/Seoul'
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
