version: "3.9"

# Create `default`
networks:
  default:
    driver: bridge

services:
  postgres:
    image: postgres:14 # don't change version
    container_name: hasura-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: always
    networks:
      - default
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - METADATA_DB=metadata
      - METADATA_USER=metadata
      - METADATA_PASSWORD=metadat
      - HASURA_DB=hasura
      - HASURA_USER=hasura
      - HASURA_PASSWORD=hasura
      - SONAR_DB=sonar
      - SONAR_USER=sonar
      - SONAR_PASSWORD=sonar
      - TEST_DB=test
      - TEST_USER=test
      - TEST_PASSWORD=test
    volumes:
      - /var/docker/init:/docker-entrypoint-initdb.d
      - /var/docker/postgresql/data:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:latest
    container_name: hasura-engine
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: always
    networks:
      - default
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_METADATA_DIR: /hasura-metadata
      HASURA_GRAPHQL_MIGRATIONS_DIR: /hasura-migrations
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
    volumes:
      - /var/docker/hasura/migrations:/hasura-migrations
      - /var/docker/hasura/metadata:/hasura-metadata
