networks:
  docker-link:
    external: true

services:
  typesense:
    image: typesense/typesense:0.23.1
    container_name: typesense-db
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8108:8108"
    networks:
      - docker-link
    environment:
      TYPESENSE_API_KEY: xyz
      TYPESENSE_DATA_DIR: /data/typesense
      TYPESENSE_ENABLE_CORS: "true"
    volumes:
      - /var/docker/typesense/data:/data/typesense
