version: "3.9"

# Create `db_net` if exists use it
networks:
  db_net:
    name: db_net
    driver: bridge

# Use `db_net`
# networks:
#   default:
#     external: true
#     name: db_net

volumes:
  html:

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
