version: '3.9'

# Create `my-net` if exists use it
networks:
  my-net:
    name: my-net
    driver: bridge

# Use `my-net`
# networks:
#   default:
#     external: true
#     name: my-net

volumes:
  html:

services:
  nginx:
    image: nginx:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - /var/docker/nginx/html:/usr/share/nginx/html
