version: '3.9'

# Create `my-net` if exists use it
networks:
  my-net:
    name: my-net
    driver: bridge

# Use `my-net`
# networks:
#   default:
#     external: true
#     name: my-net

volumes:
  html:

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
