version: "3.9"

# Create `my_net` if exists use it
networks:
  my_net:
    name: my_net
    driver: bridge

# Use `my_net`
# networks:
#   default:
#     external: true
#     name: my_net

volumes:
  html:

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
