version: '3.9'

networks:
  default:
    external: true
    name: db_net

volumes:
  html:

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
