version: '3.9'

# Create `my-net`
networks:
  my-net:
    driver: bridge

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: always
    ports:
      - 80:80
    volumes:
      - /var/docker/nginx/html:/usr/share/nginx/html
