version: "3.8"

networks:
  default:
    external: true
    name: db_net

services:
  jenkins:
    image: "jenkins/jenkins:latest"
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - TZ='Asia/Seoul'
