version: '3.9'

networks:
  default:
    name: my-net

volumes:
  jenkins:

services:
  jenkins:
    image: "jenkins/jenkins:latest"
    container_name: jenkins
    ports:
      - 8888:8080
      - 50000:50000
    user: root
    privileged: true
    environment:
      - TZ='Asia/Seoul'
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
