version: '3.9'

# Create `my-net`
networks:
  my-net:
    name: my-net
    driver: bridge

## But if `my-net` is exists, use it
# networks:
#   default:
#     external: true
#     name: my-net

services:
  jenkins:
    image: "jenkins/jenkins:latest"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: jenkins
    ports:
      - 8888:8080
      - 50000:50000
    user: root
    privileged: true
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/docker/jenkins_home:/var/jenkins_home
      - /var/docker/jenkins_home/docker.sock:/var/run/docker.sock
