version: "3.8"

services:
  jenkins:
    image: "jenkins/jenkins:latest"
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    environment:
      - TZ='Asia/Seoul'
    volumes:
      - "./jenkins_home:/tmp/jenkins_home"

volumes:
  jenkins_home:
