version: '3.9'

# Create `my-net`
networks:
  my-net:
    driver: bridge

services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - 8888:8080
      - 50000:50000
    user: root
    privileged: true
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /var/docker/jenkins_home:/var/jenkins_home
      - /var/docker/jenkins_home/docker.sock:/var/run/docker.sock
      - ./init.groovy.d:/var/jenkins_home/init.groovy.d
