version: '3.9'

# Create `default`
networks:
  default:
    driver: bridge

services:
  sonarqube-db:
    image: postgres:latest
    container_name: sonarqube-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: always
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      - DEBUG=false
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /data/postgresql/data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:8.9.9-community
    container_name: sonarqube
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: always
    depends_on:
      - sonarqube-db
    command: -Dsonar.ce.javaOpts=-Xmx1192m -Dsonar.web.javaOpts=-Xmx1192m -Dsonar.search.javaAdditionalOpts=-Dnode.store.allow_mmap=false
    ports:
      - "9000:9000"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    networks:
      - default
    environment:
      - sonar.jdbc.username=postgres
      - sonar.jdbc.password=postgres
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-db/postgres

