version: '3.7'
services:
  sonarqube-db:
    image: postgres:latest
    container_name: sonarqube-db
    ports:
      - 5432:5432
    networks:
      - quality-net
    environment:
      - DEBUG=false
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /data/postgresql/data:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:latest
    command: -Dsonar.ce.javaOpts=-Xmx1192m -Dsonar.web.javaOpts=-Xmx1192m -Dsonar.search.javaAdditionalOpts=-Dnode.store.allow_mmapfs=false
    container_name: sonarqube
    depends_on:
      - sonarqube-db
    ports:
      - 9000:9000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - quality-net
    environment:
      - sonar.jdbc.username=postgres
      - sonar.jdbc.password=postgres
      - sonar.jdbc.url=jdbc:postgresql://sonarqube-db/postgres

networks:
  quality-net:
