version: "3.9"

networks:
  db_net:
    name: db_net
    driver: bridge

# networks:
#   default:
#     external: true
#     name: db_net

services:
  mariadb:
    image: "mariadb:latest"
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - TZ='Asia/Seoul'
