version: '3.9'

networks:
  default:
    name: default
    driver: bridge

# networks:
#   default:
#     external: true
#     name: default

services:
  mariadb:
    image: 'mariadb:latest'
    container_name: mariadb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - TZ='Asia/Seoul'
