version: '3.9'

# Create `default`
networks:
  default:
    driver: bridge

services:

  postgresql-db:
    image: 'postgres:latest'
    container_name: postgresql-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: always
    ports:
      - "5432:5432"
    networks:
      - default
    environment:
      DEBUG: false
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      ADDITIONAL_DB: keycloak
      ADDITIONAL_SCHEMA: keycloak
      ADDITIONAL_USER: keycloak
      ADDITIONAL_PASSWORD: keycloak
    volumes:
      - ./init/:/docker-entrypoint-initdb.d/
    #  - /var/docker/postgresql/data:/var/lib/postgresql/data

  keycloak-iam:
    image: keycloak/keycloak:latest
    container_name: keycloak-iam
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: always
    ports:
      - "8080:8080"
    networks:
      - default
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgresql-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_USERNAME: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    # volumes:
    #   - /var/docker/keycloak/data:/opt/keycloak/data
    depends_on:
      - postgresql-db
