networks:
  docker-link:
    external: true

services:
  mysql-db:
    image: 'mysql:latest'
    container_name: mysql-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: always
    ports:
      - "3306:3306"
    networks:
      - docker-link
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - TZ='Asia/Seoul'
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - /var/docker/mysql:/docker-entrypoint-initdb.d
