version: '3.9'

# Create `my-net`
networks:
  my-net:
    driver: bridge


services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    platform: linux/amd64
    container_name: gitlab
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      TZ: 'Asia/Seoul'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - "9022:22"
      - "9080:80"
      - "9443:443"
    volumes:
      - /var/docker/gitlab/config:/etc/gitlab
      - /var/docker/gitlab/logs:/var/log/gitlab
      - /var/docker/gitlab/data:/var/opt/gitlab
