version: '3.9'

# Create `my-net`
networks:
  my-net:
    driver: bridge


services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: gitlab
    restart: always
    hostname: 'localhost'
    environment:
      TZ: 'Asia/Seoul'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:9080'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 9022:22
      - 9080:80
      - 9443:443
    volumes:
      - '/var/docker/gitlab/config:/etc/gitlab'
      - '/var/docker/gitlab/logs:/var/log/gitlab'
      - '/var/docker/gitlab/data:/var/opt/gitlab'
