version: '3.9'

networks:
  my-net:
    name: my-net
    driver: bridge

# networks:
#   default:
#     external: true
#     name: my-net

volumes:
  gitlab:

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: gitlab
    restart: always
    hostname: 'gitlab.example.com'
    environment:
      - TZ='Asia/Seoul'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - 80:80
      - 443:443
      - 22:22
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
