version: '3.9'

# Create `my-net`
networks:
  my-net:
    name: my-net
    driver: bridge

## But if `my-net` is exists, use it
# networks:
#   default:
#     external: true
#     name: my-net

services:
  pact-broker-db:
    image: 'postgres:latest'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: pact-broker-db
    ports:
      - 5432:5432
    networks:
      - my-net
    environment:
      - DEBUG=false
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/docker/postgresql/data:/var/lib/postgresql/data

  pact:
    image: pactfoundation/pact-broker
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: pact-broker
    depends_on:
      - pact-broker-db
    ports:
      - 9292:9292
    networks:
      - my-net
    environment:
      - PACT_BROKER_DATABASE_HOST=pact-broker-db
      - PACT_BROKER_DATABASE_NAME=postgres
      - PACT_BROKER_DATABASE_PORT=5432
      - PACT_BROKER_DATABASE_SSLMODE=disable
      - PACT_BROKER_DATABASE_PASSWORD=postgres
      - PACT_BROKER_DATABASE_USERNAME=postgres
      - PACT_BROKER_BASIC_AUTH_USERNAME=admin
      - PACT_BROKER_BASIC_AUTH_PASSWORD=admin
      - PACT_BROKER_ALLOW_PUBLIC_READ=true
