version: '3.9'

# Create `my-net`
networks:
  my-net:
    driver: bridge

services:
  redis-db:
    image: redis:latest
    container_name: redis-db
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    restart: always
    ports:
      - 6379:6379
    labels:
      - name=redis
      - mode=standalone
    volumes:
      - /var/docker/redis:/redis
