version: '3.9'

# Create `my-net` if exists use it
networks:
  my-net:
    name: my-net
    driver: bridge

volumes:
  data:

services:
  redis-db:
    image: redis:latest
    container_name: redis-db
    ports:
      - 6379:6379
    labels:
      - name=redis
      - mode=standalone
    volumes:
      - ./data:/data
