version: '3.9'

# Create `my-net`
networks:
  my-net:
    name: my-net
    driver: bridge

## But if `my-net` is exists, use it
# networks:
#   default:
#     external: true
#     name: my-net

services:
  redis-db:
    image: redis:latest
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    container_name: redis-db
    ports:
      - 6379:6379
    labels:
      - name=redis
      - mode=standalone
    volumes:
      - /var/docker/redis:/redis
